export const goods = [
  { name: 'Big Mac', price: '2', img: '/big-mac.jpg' },
  { name: 'Flip Flop', price: '3', img: '/flip-flops.jpg' },
  { name: 'Coca-Cola Pack', price: '5', img: '/coca-cola-pack.jpg' },
  { name: 'Movie Ticket', price: '12', img: '/movie-ticket.jpg' },
  { name: 'Book', price: '15', img: '/book.jpg' },
  { name: 'Lobster Dinner', price: '45', img: '/lobster-dinner.jpg' },
  { name: 'Video Game', price: '60', img: '/video-game.jpg' },
  { name: 'Amazon Echo', price: '99', img: '/amazon-echp.jpg' },
  { name: 'Year of Netflix', price: '100', img: '/year-of-netflix.jpg' },
  { name: 'Air Jordans', price: '125', img: '/air-jordans.jpg' },
  { name: 'Airpods', price: '199', img: '/airpods.jpg' },
  { name: 'Gaming Console', price: '299', img: '/gaming-console.jpg' },
  { name: 'Drone', price: '350', img: '/drone.jpg' },
  { name: 'Smartphone', price: '699', img: '/smartphone.jpg' },
  { name: 'Bike', price: '800', img: '/bike.jpg' },
  { name: 'Kitten', price: '1500', img: '/kitten.jpg' },
  { name: 'Puppy', price: '1500', img: '/puppy.jpg' },
  { name: 'Auto Rickshaw', price: '2300', img: '/auto-rickshaw.jpg' },
  { name: 'Horse', price: '2500', img: '/horse.jpg' },
  { name: 'Acre of Farmland', price: '3000', img: '/acre-of-farmland.jpg' },
  { name: 'Designer Handbag', price: '5500', img: '/designer-handbag.jpg' },
  { name: 'Hot Tub', price: '6000', img: '/hot-tub.jpg' },
  { name: 'Luxury Wine', price: '7000', img: '/luxury-wine.jpg' },
  { name: 'Diamond Ring', price: '10000', img: '/diamond-ring.jpg' },
  { name: 'Jet Ski', price: '12000', img: '/jet-ski.jpg' },
  { name: 'Rolex', price: '15000', img: '/rolex.jpg' },
  { name: 'Ford F-150', price: '30000', img: '/ford-f-150.jpg' },
  { name: 'Tesla', price: '75000', img: '/tesla.jpg' },
  { name: 'Monster Truck', price: '150000', img: '/monster-truck.jpg' },
  { name: 'Ferrari', price: '250000', img: '/ferrari.jpg' },
  { name: 'Single Family Home', price: '300000', img: '/single-family-home.jpg' },
  { name: 'Gold Bar', price: '700000', img: '/gold-bar.jpg' },
  { name: 'McDonalds Franchise', price: '1500000', img: '/mcdonalds-franchise.jpg' },
  { name: 'Superbowl Ad', price: '5250000', img: '/superbowl-ad.jpg' },
  { name: 'Yacht', price: '7500000', img: '/yacht.jpg' },
  { name: 'M1 Abrams', price: '8000000', img: '/m1-abrams.jpg' },
  { name: 'Formula 1 Car', price: '15000000', img: '/formula-1-car.jpg' },
  { name: 'Apache Helicopter', price: '31000000', img: '/apache-helicopter.jpg' },
  { name: 'Mansion', price: '45000000', img: '/mansion.jpg' },
  { name: 'Make a Movie', price: '100000000', img: '/make-a-movie.jpg' },
  { name: 'Boeing 747', price: '148000000', img: '/boeing-747.jpg' },
  { name: 'Mona Lisa', price: '780000000', img: '/mona-lisa.jpg' },
  { name: 'Skyscraper', price: '850000000', img: '/skyscraper.jpg' },
  { name: 'Cruise Ship', price: '930000000', img: '/cruise-ship.jpg' },
  { name: 'NBA Team', price: '2120000000', img: '/nba-team.jpg' },
];
